### PR TITLE
fix(TDI-42310): S3 connector should be able to leverage public S3 buckets

### PR DESCRIPTION
**Pull request by wwang-talend**

### CODE REVIEW

**Review by RyanSkraba — APPROVED** [review]
LGTM -- but can you create a new tlnd-2.7.3.2-SNAPSHOT branch?

We never did a 2.7.3.1 release, we just recopied the SNAPSHOT jar with a release name!

**Comment by wwang-talend** [comment]
sure, will do it

**Comment by wwang-talend** [comment]
i have no permits for this repository
```
Pushing to https://github.com/Talend/hadoop.git
remote: Permission to Talend/hadoop.git denied to wwang-talend.
fatal: unable to access 'https://github.com/Talend/hadoop.git/': The requested URL returned error: 403
```
so seems can't create the new branch : tlnd-2.7.3.2-SNAPSHOT

**Comment by wwang-talend** [comment]
will close the pull request, as only need a new branch with the name : tlnd-2.7.3.2-SNAPSHOT 
https://github.com/Talend/hadoop/compare/tlnd-2.7.3.1-SNAPSHOT...Talend:tlnd-2.7.3.2-SNAPSHOT?expand=1

**Pull request closed without merging**
